<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CounterNumberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $counters = [
            [
                'screen_id' => 'MBD01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 24,
                'seq_nm' => null,
                'note' => 'Master Brand',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:08',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MDR01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 2,
                'seq_nm' => null,
                'note' => 'Master Dealers',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:08',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MPE01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 6,
                'seq_nm' => null,
                'note' => 'Master Permission',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:08',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MRO01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 6,
                'seq_nm' => null,
                'note' => 'Master Role',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:08',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MRP01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 1,
                'seq_nm' => null,
                'note' => 'Master Role Permission',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:08',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MUB01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 3,
                'seq_nm' => null,
                'note' => 'Master User Brands',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:20',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MUR01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 23,
                'seq_nm' => null,
                'note' => 'Master User Roles',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:08',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MUS01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 3,
                'seq_nm' => null,
                'note' => 'Master User',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:08',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'ZLG01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'PO',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 1,
                'seq_nm' => null,
                'note' => 'Login',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:20',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '/',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MRM01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 1,
                'seq_nm' => null,
                'note' => 'Master Role Menu',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:20',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
            [
                'screen_id' => 'MMN01',
                'max_digit' => 20,
                'cnt_date' => null,
                'cnt_date_fmt' => '%y%m%d',
                'ptn_prefix' => 'MS',
                'ptn_suffix' => null,
                'curr_value' => '000000000000000',
                'max_value' => '999999999999999',
                'min_value' => '000000000000000',
                'seq_flg' => 15,
                'seq_nm' => null,
                'note' => 'Master Menu',
                'category_cd' => null,
                'ins_ts' => '2024-09-25 00:00:00',
                'ins_usr_id' => 'system',
                'upd_cntr' => 0,
                'upd_ts' => '2024-09-25 16:01:20',
                'upd_usr_id' => 'system',
                'key_elm' => null,
                'c_cnt_ptn' => '-',
                'digit' => 5,
            ],
        ];

        foreach ($counters as $counter) {
            DB::table('ms_counter_number')->insert($counter);
        }

        $this->command->info('Counter number seeded successfully!');
    }
}
