<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TransactionBodySeeder extends Seeder
{
    public function run(): void
    {
        $bodies = [
            [
                'part_no' => 'PART-001',
                'invoice_no' => 1001,
                'description' => 'Engine Oil Filter',
                'qty' => 2.00,
                'selling_price' => 150000.00,
                'discount' => 0.10,
                'extended_price' => 270000.00,
                'menu_price' => 150000.00,
                'vat' => 'Y',
                'menu_vat' => 'Y',
                'cost_price' => 120000.00,
                'analysis_code' => 'A',
                'invoice_status' => 'C',
                'unit' => 'Each',
                'mins_per_unit' => 30,
                'wip_no' => 2001,
                'line' => 1,
                'account_code' => 'ACC001',
                'department' => 'Service',
                'franchise_code' => 'FR1',
                'sales_type' => 'R',
                'warranty_code' => 'W01',
                'menu_flag' => 'Y',
                'contribution' => 0.20,
                'date_decard' => '2026-01-15',
                'magic_1' => 100,
                'magic_2' => 200,
                'po_no' => 5001,
                'grn_no' => 6001,
                'menu_code' => 1,
                'labour_rates' => 'A',
                'supplier_code' => 'SUP001',
                'menu_link' => 1,
                'currency_price' => 150000.00,
                'part_or_labour' => 'P',
                'created_by' => 1,
                'unique_id' => (string) Str::uuid(),
                'is_active' => '1',
            ],
            [
                'part_no' => 'LAB-001',
                'invoice_no' => 1001,
                'description' => 'Labour - Oil Change Service',
                'qty' => 1.00,
                'selling_price' => 200000.00,
                'discount' => 0.00,
                'extended_price' => 200000.00,
                'menu_price' => 200000.00,
                'vat' => 'Y',
                'menu_vat' => 'Y',
                'cost_price' => 150000.00,
                'analysis_code' => 'B',
                'invoice_status' => 'C',
                'unit' => 'Hour',
                'mins_per_unit' => 60,
                'wip_no' => 2001,
                'line' => 2,
                'account_code' => 'ACC001',
                'department' => 'Service',
                'franchise_code' => 'FR1',
                'sales_type' => 'R',
                'warranty_code' => 'W01',
                'menu_flag' => 'Y',
                'contribution' => 0.25,
                'date_decard' => '2026-01-15',
                'magic_1' => 100,
                'magic_2' => 200,
                'po_no' => null,
                'grn_no' => null,
                'menu_code' => 2,
                'labour_rates' => 'A',
                'supplier_code' => null,
                'menu_link' => 0,
                'currency_price' => 200000.00,
                'part_or_labour' => 'L',
                'created_by' => 1,
                'unique_id' => (string) Str::uuid(),
                'is_active' => '1',
            ],
            [
                'part_no' => 'PART-002',
                'invoice_no' => 1002,
                'description' => 'Brake Pad Front',
                'qty' => 1.00,
                'selling_price' => 500000.00,
                'discount' => 0.05,
                'extended_price' => 475000.00,
                'menu_price' => 500000.00,
                'vat' => 'Y',
                'menu_vat' => 'Y',
                'cost_price' => 400000.00,
                'analysis_code' => 'A',
                'invoice_status' => 'X',
                'unit' => 'Set',
                'mins_per_unit' => 45,
                'wip_no' => 2002,
                'line' => 1,
                'account_code' => 'ACC002',
                'department' => 'Service',
                'franchise_code' => 'FR1',
                'sales_type' => 'R',
                'warranty_code' => 'W02',
                'menu_flag' => 'N',
                'contribution' => 0.15,
                'date_decard' => '2026-01-20',
                'magic_1' => 101,
                'magic_2' => 201,
                'po_no' => 5002,
                'grn_no' => 6002,
                'menu_code' => 3,
                'labour_rates' => 'B',
                'supplier_code' => 'SUP002',
                'menu_link' => 1,
                'currency_price' => 500000.00,
                'part_or_labour' => 'P',
                'created_by' => 1,
                'unique_id' => (string) Str::uuid(),
                'is_active' => '1',
            ],
        ];

        foreach ($bodies as $body) {
            DB::table('tx_body')->insert($body);
        }
    }
}
